package com.dym.film.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ATTENTION_AUTHOR".
 */
public class AttentionAuthor implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String AttentionAuthorId;
    private String AttentionAuthorDes;

    public AttentionAuthor() {
    }

    public AttentionAuthor(Long id) {
        this.id = id;
    }

    public AttentionAuthor(Long id, String AttentionAuthorId, String AttentionAuthorDes) {
        this.id = id;
        this.AttentionAuthorId = AttentionAuthorId;
        this.AttentionAuthorDes = AttentionAuthorDes;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAttentionAuthorId() {
        return AttentionAuthorId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAttentionAuthorId(String AttentionAuthorId) {
        this.AttentionAuthorId = AttentionAuthorId;
    }

    public String getAttentionAuthorDes() {
        return AttentionAuthorDes;
    }

    public void setAttentionAuthorDes(String AttentionAuthorDes) {
        this.AttentionAuthorDes = AttentionAuthorDes;
    }

}
