package com.dym.film.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CINEMA".
 */
public class cinema implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String cinemaID;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String address;
    private String tel;
    private String minPrice;
    private String lng;
    private String lat;

    public cinema() {
    }

    public cinema(Long id) {
        this.id = id;
    }

    public cinema(Long id, String cinemaID, String name, String address, String tel, String minPrice, String lng, String lat) {
        this.id = id;
        this.cinemaID = cinemaID;
        this.name = name;
        this.address = address;
        this.tel = tel;
        this.minPrice = minPrice;
        this.lng = lng;
        this.lat = lat;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCinemaID() {
        return cinemaID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCinemaID(String cinemaID) {
        this.cinemaID = cinemaID;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String address) {
        this.address = address;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getMinPrice() {
        return minPrice;
    }

    public void setMinPrice(String minPrice) {
        this.minPrice = minPrice;
    }

    public String getLng() {
        return lng;
    }

    public void setLng(String lng) {
        this.lng = lng;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

}
