package com.dym.film.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.QueryBuilder;

import com.dym.film.entity.FilmReview;
import com.dym.film.manager.DatabaseManager;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FILM_REVIEW".
*/
public class FilmReviewDao extends AbstractDao<FilmReview, Long> {

    public static final String TABLENAME = "FILM_REVIEW";

    /**
     * Properties of entity FilmReview.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FilmReviewId = new Property(1, String.class, "FilmReviewId", false, "FILM_REVIEW_ID");
        public final static Property FilmReviewDes = new Property(2, String.class, "FilmReviewDes", false, "FILM_REVIEW_DES");
    };


    public FilmReviewDao(DaoConfig config) {
        super(config);
    }
    
    public FilmReviewDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FILM_REVIEW\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FILM_REVIEW_ID\" TEXT NOT NULL ," + // 1: FilmReviewId
                "\"FILM_REVIEW_DES\" TEXT);"); // 2: FilmReviewDes
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FILM_REVIEW\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FilmReview entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getFilmReviewId());
 
        String FilmReviewDes = entity.getFilmReviewDes();
        if (FilmReviewDes != null) {
            stmt.bindString(3, FilmReviewDes);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FilmReview readEntity(Cursor cursor, int offset) {
        FilmReview entity = new FilmReview( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // FilmReviewId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // FilmReviewDes
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FilmReview entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFilmReviewId(cursor.getString(offset + 1));
        entity.setFilmReviewDes(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FilmReview entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FilmReview entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }



    /**
     * 保存消息到数据库ng
     * 如果本地保存的消息超过20条，删除最老的条
     * @param message
     */
    public void saveUserFilmReview(FilmReview message)
    {
        DaoSession session = DatabaseManager.getInstance().getDaoSession();
        if (session != null) {
            FilmReviewDao dao = session.getFilmReviewDao();
            try {
                if(isSaved(dao,message.getFilmReviewId())){
                    isDeleted(dao,message.getFilmReviewId());
                    dao.insert(message);
                }
                else{
                    dao.insert(message);
                }
            }
            catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * 查询某个表是否包含某个id:
     * @param ID
     * @return
     */
    public boolean isSaved(FilmReviewDao dao ,String ID)
    {
        QueryBuilder<FilmReview> qb = dao.queryBuilder();
        qb.where(Properties.FilmReviewId.eq(ID));
        qb.buildCount().count();
        return qb.buildCount().count() > 0 ? true : false;
    }

    /**
     * 查询某个表是否包含某个id:
     * @param ID
     * @return
     */
    public void isDeleted(FilmReviewDao dao ,String ID)
    {
        QueryBuilder<FilmReview> qb = dao.queryBuilder();
        qb.where(Properties.FilmReviewId.eq(ID));
        qb.buildCount().count();
        if(qb.buildCount().count() > 0 ? true : false)
            dao.deleteByKey(qb.list().get(0).getId());
    }

    /**
     * 查询所有
     * @param dao
     * @return
     */
    public List<FilmReview> getFilmReviewList(FilmReviewDao dao,int i)
    {
        if(i==-1){
            QueryBuilder<FilmReview> qb = dao.queryBuilder();
            qb.orderDesc(Properties.Id);
            return qb.list();
        }else {
            QueryBuilder<FilmReview> qb = dao.queryBuilder();
            qb.orderDesc(Properties.Id).limit(i);
            return qb.list();
        }
    }
    /**
     * 删除前5条
     * @param dao
     * @return
     */
    public void delectFilmReviewList(FilmReviewDao dao)
    {
        QueryBuilder<FilmReview> qb = dao.queryBuilder();
        qb.limit(5);
        for (FilmReview FilmReview:qb.list()){
            dao.delete(FilmReview);
        }
    }

}
